# Generated by Django 5.1.2 on 2024-11-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_appuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
