# Generated by Django 5.1.2 on 2024-11-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_appuser_groups_appuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='date_joined',
        ),
    ]
