# Generated by Django 5.1.2 on 2024-11-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_appuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
