# Generated by Django 5.1.2 on 2024-11-20 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_city_country_remove_city_state_delete_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
