# Generated by Django 5.1.2 on 2024-11-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_appuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='updated_at',
        ),
    ]
