# Generated by Django 5.1.2 on 2024-11-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_appuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
